const fs = require('fs');

const jsonFile = process.argv[2];
const mdFile = process.argv[3];

if (!jsonFile || !mdFile) {
    console.error("Usage: node render_matrix.js <input.json> <output.md>");
    process.exit(1);
}

const data = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));

let md = `# Master Traceability Matrix\n\n`;
md += `**Generated:** ${new Date().toISOString()}\n\n`;
md += `> This document maps the relationships between Hazards, System Requirements, and User Journeys. It is automatically generated by the CI/CD pipeline.\n\n`;

md += `## Traceability Health Dashboard\n\n`;
const totalTags = data.trace_tags.length;
const isolatedTags = data.verificationErrors.isolated.length;
const duplicateTags = data.verificationErrors.duplicates.length;
const danglingTags = data.verificationErrors.dangling.length;

md += `| Metric | Count | Status |\n`;
md += `|---|---|---|\n`;
md += `| **Total Traced Nodes** | ${totalTags} | 🔵 |\n`;
md += `| **Isolated Nodes** (Missing Links) | ${isolatedTags} | ${isolatedTags > 0 ? '🔴 Warning' : '🟢 Pass'} |\n`;
md += `| **Duplicate IDs** | ${duplicateTags} | ${duplicateTags > 0 ? '🔴 Critical' : '🟢 Pass'} |\n`;
md += `| **Dangling References** | ${danglingTags} | ${danglingTags > 0 ? '🔴 Critical' : '🟢 Pass'} |\n\n`;

// Build file map
const filesMap = {};
data.files.forEach(f => {
    let relative = f.file;
    const match = relative.match(/\/docs\/(.*)/);
    if (match) relative = 'docs/' + match[1];
    filesMap[f.file_id] = relative;
});

// Build tags list grouped by layer
data.layers.forEach(layer => {
    md += `## ${layer.name} Layer\n\n`;
    const layerTags = data.trace_tags.filter(t => t.layer_id === layer.layer_id);
    if (layerTags.length === 0) {
        md += `*No tags found in this layer.*\n\n`;
        return;
    }

    // Sort alphabetically by ID
    layerTags.sort((a, b) => a.id.localeCompare(b.id));

    if (layer.upstream_layers.length > 0) {
        md += `| Tag ID | Description | Source File | Traces To (Upstream) |\n`;
        md += `|---|---|---|---|\n`;
        layerTags.forEach(t => {
            const upstreams = t.from_tags.join(', ') || '-';
            const cleanDesc = t.description.replace(/^REQ-[A-Z]+-\d+: /, '').replace(/^### /, '').replace(/^H-\d+: /, '').replace(/\*\*Requirement:\*\*/g, '').replace(/\*\*Hazard:\*\*/g, '').replace(/\n/g, ' ').trim().substring(0, 150);
            md += `| **${t.id.replace(/@/g, '')}** | ${cleanDesc} | \`${filesMap[t.file_id]}\` | ${upstreams.replace(/@/g, '')} |\n`;
        });
    } else {
        md += `| Tag ID | Description | Source File |\n`;
        md += `|---|---|---|\n`;
        layerTags.forEach(t => {
            const cleanDesc = t.description.replace(/^REQ-[A-Z]+-\d+: /, '').replace(/^### /, '').replace(/^H-\d+: /, '').replace(/\*\*Requirement:\*\*/g, '').replace(/\*\*Hazard:\*\*/g, '').replace(/\n/g, ' ').trim().substring(0, 150);
            md += `| **${t.id.replace(/@/g, '')}** | ${cleanDesc} | \`${filesMap[t.file_id]}\` |\n`;
        });
    }
    md += `\n`;
});

fs.writeFileSync(mdFile, md, 'utf8');
console.log('Markdown Matrix successfully generated!');
