const fs = require('fs');

const jsonFile = process.argv[2];
const htmlFile = process.argv[3];

if (!jsonFile || !htmlFile) {
    console.error("Usage: node render_matrix.js <input.json> <output.html>");
    process.exit(1);
}

const data = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));

let html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Master Traceability Matrix</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; padding: 20px; max-width: 1200px; margin: 0 auto; color: #333; }
        h1, h2 { color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 10px; }
        .dashboard { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }
        .card { background: #f8f9fa; border: 1px solid #dee2e6; border-radius: 8px; padding: 20px; text-align: center; }
        .card h3 { margin: 0 0 10px 0; font-size: 1.2em; color: #6c757d; }
        .card p { margin: 0; font-size: 2em; font-weight: bold; }
        .status-pass { color: #28a745; }
        .status-warn { color: #ffc107; }
        .status-crit { color: #dc3545; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { border: 1px solid #dee2e6; padding: 12px; text-align: left; }
        th { background: #f8f9fa; font-weight: bold; color: #495057; }
        tr:nth-child(even) { background: #f8f9fa; }
        code { background: #e9ecef; padding: 2px 4px; border-radius: 4px; font-family: monospace; font-size: 0.9em; }
    </style>
</head>
<body>
    <h1>Master Traceability Matrix</h1>
    <p><strong>Generated:</strong> ${new Date().toISOString()}</p>
    <p>This document maps the relationships between Hazards, System Requirements, and User Journeys. It is automatically generated by the CI/CD pipeline.</p>
`;

const totalTags = data.trace_tags.length;
const isolatedTags = data.verificationErrors.isolated.length;
const duplicateTags = data.verificationErrors.duplicates.length;
const danglingTags = data.verificationErrors.dangling.length;

html += `
    <h2>Traceability Health Dashboard</h2>
    <div class="dashboard">
        <div class="card">
            <h3>Total Traced Nodes</h3>
            <p style="color: #007bff">${totalTags}</p>
        </div>
        <div class="card">
            <h3>Isolated Nodes</h3>
            <p class="${isolatedTags > 0 ? 'status-warn' : 'status-pass'}">${isolatedTags}</p>
        </div>
        <div class="card">
            <h3>Duplicate IDs</h3>
            <p class="${duplicateTags > 0 ? 'status-crit' : 'status-pass'}">${duplicateTags}</p>
        </div>
        <div class="card">
            <h3>Dangling References</h3>
            <p class="${danglingTags > 0 ? 'status-crit' : 'status-pass'}">${danglingTags}</p>
        </div>
    </div>
`;

// Build file map
const filesMap = {};
data.files.forEach(f => {
    let relative = f.file;
    const match = relative.match(/\/docs\/(.*)/);
    if (match) relative = 'docs/' + match[1];
    filesMap[f.file_id] = relative;
});

// Build tables
data.layers.forEach(layer => {
    html += `    <h2>${layer.name} Layer</h2>\n`;
    const layerTags = data.trace_tags.filter(t => t.layer_id === layer.layer_id);
    if (layerTags.length === 0) {
        html += `    <p><em>No tags found in this layer.</em></p>\n`;
        return;
    }

    // Sort alphabetically by ID
    layerTags.sort((a, b) => a.id.localeCompare(b.id));

    html += `    <table>\n        <thead>\n            <tr>\n`;
    html += `                <th>Tag ID</th>\n                <th>Description</th>\n                <th>Source File</th>\n`;
    if (layer.upstream_layers.length > 0) {
        html += `                <th>Traces To (Upstream)</th>\n`;
    }
    html += `            </tr>\n        </thead>\n        <tbody>\n`;

    layerTags.forEach(t => {
        const upstreams = t.from_tags.join(', ') || '-';
        const cleanDesc = t.description.replace(/^REQ-[A-Z]+-\d+: /, '').replace(/^### /, '').replace(/^H-\d+: /, '').replace(/\*\*Requirement:\*\*/g, '').replace(/\*\*Hazard:\*\*/g, '').replace(/\n/g, ' ').trim().substring(0, 150);
        html += `            <tr>\n`;
        html += `                <td><strong>${t.id.replace(/@/g, '')}</strong></td>\n`;
        html += `                <td>${cleanDesc}</td>\n`;
        html += `                <td><code>${filesMap[t.file_id]}</code></td>\n`;
        if (layer.upstream_layers.length > 0) {
            html += `                <td>${upstreams.replace(/@/g, '')}</td>\n`;
        }
        html += `            </tr>\n`;
    });
    html += `        </tbody>\n    </table>\n`;
});

html += `
</body>
</html>`;

fs.writeFileSync(htmlFile, html, 'utf8');
console.log('HTML Matrix successfully generated!');
